import { ReactNode } from "react";
import Sidebar from "./Sidebar";
import { Metadata } from "next";

interface LayoutProps {
  children: ReactNode;
}
export const metadata: Metadata = {
  title: "Mailprex1",
  description: "Generated by create next app",
};

const DocsLayout = ({ children }: LayoutProps) => {
  return (
    <div className="flex min-h-screen pt-16">
      <Sidebar />
      <div className="flex-1 p-8">{children}</div>
    </div>
  );
};

export default DocsLayout;
